[settings]
experimental = true

[tools]
yamllint = "latest"
deno = "1.46"
yamlfmt = "latest"

[tasks."check:format"]
run = """
set -ex

deno fmt --check
yamlfmt -dry -lint $(find . -name '*.yaml')
"""

[tasks."check:lint"]
run = """
set -ex

deno lint
deno check --no-lock $(find . -name '*.ts' -o -name '*.tsx')
deno run -A --no-lock npm:markdownlint-cli2 "**/*.{md,markdown}"
yamllint $(find . -name '*.yaml')
"""
